name: Build and Deploy Site

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    name: Build and Deploy GitHub Pages
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: build

      - name: Set up Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          build_revision: ${{ github.sha }}
          verbose: true

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1

      - name: Archive Artifact
        run: |
          tar -cvf artifact.tar -C ./_site .
          mv artifact.tar ${{ runner.temp }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages

      - name: Clean Up
        run: git clean -fdx

