name: Build and Deploy to GitHub Pages

on:
  push:
    branches: 
      - dev  # Adjust this as necessary to your development branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust this as necessary to match your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Ensure this script outputs to a 'dist' directory or similar

      - name: Upload build artifacts for deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # This name must match the expected artifact name in the deploy job
          path: ./dist  # Adjust this path to where your build script outputs files

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
